name: CI/CD Pipeline (AWS)

#on:
#  push:
#    branches: [ branch1 ]
on: workflow_dispatch

jobs:
  #security-scan:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: SonarQube Scan
  #      uses: SonarSource/sonarqube-scan-action@v6
  #      env:
  #        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #        SONAR_HOST_URL: https://sonarcloud.io
  #      with:
  #        args: >
  #          -Dsonar.projectKey=shaxeb92_ToDoApp
  #          -Dsonar.organization=shaxeb92
  #          -Dsonar.host.url=https://sonarcloud.io
  #          -Dsonar.sources=.
  #          -Dsonar.exclusions=node_modules/**,*.test.js,*.spec.js
  #        cache: false

  build-deploy:
   # needs: security-scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      # Configure AWS Credentials via OIDC (no static keys!)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: us-east-1

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build & Push
      - name: Build, Tag, Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/devops-todo-app:$IMAGE_TAG .
          docker push $ECR_REGISTRY/devops-todo-app:$IMAGE_TAG

      # Update Kubeconfig
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name devops-eks --region us-east-1

      # Debug: Who am I?
      - name: Check AWS Identity
        run: aws sts get-caller-identity

      # Deploy
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/todoapp-deployment \
            todo=${{ steps.login-ecr.outputs.registry }}/devops-todo-app:${{ github.sha }} -n default
          kubectl rollout status deployment/todoapp-deployment -n default
